### ISSUE TITLE
Lazylibrarian homepage link

### ISSUE THREAD

**Issue by philborman** [Thraxis/docker-lazylibrarian-calibre#1]
Hi,
I just added a link to your docker on the lazylibrarian home page, hope that's ok, if not I will remove it. We had a user trying to get calibredb in one docker to talk to lazylibrarian in another docker. Your solution is much neater.

**Comment by Thraxis** [comment]
No it's not a problem.  I do actually need to update the docker some as I haven't accounted for the new audiobook folder yet.
